version: "3"

services:
  db:
    container_name: db_pmangas
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: pgmangas
  adminer:
    container_name: adminer_pmangas
    image: adminer
    restart: always
    ports:
      - 8080:8080
  #api:
  #  container_name: api_pmangas
  #  build: ./backend
  #  restart: always
  #  command: npm start
  #  ports:
  #    - "3333:3333"
  #  volumes:
  #    - ./backend:/usr/app
  #  depends_on:
  #    - db
